/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package signup;

import connection.SQLConnection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import login.Login;
/**
 *
 * @author Sovandy
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginHeader = new javax.swing.JPanel();
        LoginText = new javax.swing.JLabel();
        CloseText = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        UsernameText = new javax.swing.JLabel();
        PasswordText = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        FistnameText = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        LastnameText = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        GenderText = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LoginHeader.setBackground(new java.awt.Color(244, 180, 26));
        LoginHeader.setForeground(new java.awt.Color(244, 180, 26));
        LoginHeader.setToolTipText("");

        LoginText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LoginText.setForeground(new java.awt.Color(255, 255, 255));
        LoginText.setText("SignUp");

        CloseText.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        CloseText.setForeground(new java.awt.Color(242, 242, 242));
        CloseText.setText("X");
        CloseText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginHeaderLayout = new javax.swing.GroupLayout(LoginHeader);
        LoginHeader.setLayout(LoginHeaderLayout);
        LoginHeaderLayout.setHorizontalGroup(
            LoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginHeaderLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(LoginText)
                .addGap(193, 193, 193)
                .addComponent(CloseText)
                .addContainerGap())
        );
        LoginHeaderLayout.setVerticalGroup(
            LoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginHeaderLayout.createSequentialGroup()
                .addComponent(CloseText)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LoginHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LoginText)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Main.setBackground(new java.awt.Color(20, 61, 89));

        UsernameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameText.setForeground(new java.awt.Color(242, 242, 242));
        UsernameText.setText("Username");

        PasswordText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordText.setForeground(new java.awt.Color(242, 242, 242));
        PasswordText.setText("Password");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUsername.setToolTipText("");

        btnSignUp.setBackground(new java.awt.Color(0, 153, 0));
        btnSignUp.setForeground(new java.awt.Color(242, 242, 242));
        btnSignUp.setText("SignUp");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(0, 102, 255));
        btnLogin.setForeground(new java.awt.Color(242, 242, 242));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPassword.setToolTipText("");

        FistnameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FistnameText.setForeground(new java.awt.Color(242, 242, 242));
        FistnameText.setText("Firstname");

        txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtFirstname.setToolTipText("");

        LastnameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastnameText.setForeground(new java.awt.Color(242, 242, 242));
        LastnameText.setText("Lastname");

        txtLastname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLastname.setToolTipText("");

        GenderText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GenderText.setForeground(new java.awt.Color(242, 242, 242));
        GenderText.setText("Gender");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GenderText)
                    .addComponent(txtLastname)
                    .addComponent(LastnameText)
                    .addComponent(txtFirstname)
                    .addComponent(FistnameText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                        .addComponent(btnSignUp)
                        .addGap(229, 229, 229)
                        .addComponent(btnLogin))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PasswordText)
                        .addComponent(txtPassword)
                        .addComponent(txtUsername)
                        .addComponent(UsernameText))
                    .addComponent(cbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(FistnameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LastnameText)
                .addGap(18, 18, 18)
                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GenderText)
                .addGap(18, 18, 18)
                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordText)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseTextMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseTextMouseClicked

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        String firstName = txtFirstname.getText();
        String lastName = txtLastname.getText();
        String gender = (String)cbGender.getSelectedItem();
        String username = txtUsername.getText().toLowerCase(); //Get name from textbox and store in Variable
        String password = new String(txtPassword.getPassword()).toLowerCase();//Get password from pass-box and store in Variable
        
        if(firstName.equals("") || lastName.equals("") || gender.equals("") || username.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null, "Field Cannot Be Empty!");//null is use to make message-box at the middle of the screen
        }else{
            
            if(checkExistingUsername(username)){
                JOptionPane.showMessageDialog(null, "Username Already Exist! Please Enter New Username.");
            }else{
                String query = "INSERT INTO Account(firstname,lastname,gender,balance,username,password) values (?,?,?,?,?,?)";
                try {
                    PreparedStatement pst = SQLConnection.getConnection().prepareStatement(query);
                    pst.setString(1, firstName);
                    pst.setString(2, lastName);
                    pst.setString(3, gender);
                    pst.setString(4, "0");
                    pst.setString(5, username);
                    pst.setString(6, password);

                    if(pst.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null, "SignUp Success! Please Login!");

                    this.setVisible(false);
                    Login login = new Login();
                    login.pack();
                    login.setLocationRelativeTo(null);
                    login.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "SignUp Failed!");
                    }

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "SignUp Failed!");
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnSignUpMouseClicked
    
    private boolean checkExistingUsername(String username){
        
        String query = "SELECT * FROM Account Where username = ?";
        try {
            PreparedStatement pst = SQLConnection.getConnection().prepareStatement(query);
            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                return true;
            }  
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Login login = new Login();
        login.pack();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseText;
    private javax.swing.JLabel FistnameText;
    private javax.swing.JLabel GenderText;
    private javax.swing.JLabel LastnameText;
    private javax.swing.JPanel LoginHeader;
    private javax.swing.JLabel LoginText;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel PasswordText;
    private javax.swing.JLabel UsernameText;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
